### ISSUE TITLE
Binary Bot Stop Without Reason

### ISSUE THREAD

**Issue by virtusasys** [binary-com/binary-bot#3016] opened 2020-09-28 19:34 UTC
Why Binary Bot Stop Without Reason
every unsuccessfully bot run continuously
but bot is run successfull bot is stop .
what is the reason

**Comment by deny-titan** [comment] 2020-09-29 00:58
Hi @virtusasys 

Is your problem look similar on this issue : #2998 ?

**Comment by aaron-binary** [comment] 2020-09-29 01:31
Hey @virtusasys,

@deny-titan has previously reported a similar issue (#2998) which has highlighted an issue on our side. 

We're currently working on fixing this will issue a release asap.

Regards,
Aaron

**Comment by Kosta92** [comment] 2020-09-29 14:10
This has been going on for a long time. It happens with both the Continuous Indices and the Daily Reset Indices, but I've noticed that it happens more often with Daily Reset Indices.

**Comment by aaron-binary** [comment] 2020-09-30 03:01
Hey @Kosta92,

We're in the process of preparing some fixes that will address these issues.

My apologies for the inconvenience this has caused.

Regards,
Aaron

**Comment by aaron-binary** [comment] 2020-09-30 08:23
Hey @virtusasys @deny-titan @Kosta92,

We've released some fixes, could you confirm whether or not you're still experiencing any difficulties trading?

Thanks again for your feedback.

Regards,
Aaron

**Comment by Kosta92** [comment] 2020-09-30 12:10
@aaron-binary I'll let you know in a few days because it doesn't happen all the time.

**Comment by virtusasys** [comment] 2020-09-30 18:50
@aaron-binary yes.. still same .

**Comment by Kosta92** [comment] 2020-10-01 20:06
Happened again:

![Bot](https://user-images.githubusercontent.com/11698414/94857085-3ab85680-0431-11eb-8b78-68981d48fdde.png)

I've noticed that it freezes more often while closing the contract compared to opening the contract. Strange thing is that it actually closes the contract, but the status never changes to _Settled_. As you can see in the provided screenshot, the contract has an entry spot and an exit spot, therefore it's been done, but it freezes when changing the status from _Pending_ to _Settled_.

**Comment by aaron-binary** [comment] 2020-10-02 03:42
Hey @Kosta92,

Could you share the strategy that you use to produce this behaviour?

We're actively looking into this.

Regards,
Aaron

**Comment by deja12** [comment] 2020-10-02 11:21
I am having the same issue with 1 tick odd even bot. bot just stop sometimes after 1 trade and sometimes after 5 to 10 trades. with using martingale its very dangerous to run. Please help me... I am start seeing this error from last three days...

**Comment by deja12** [comment] 2020-10-06 03:57
@aaron-binary problem is getting worse, now it stop after every two or three trades.. when you people are going to fix it?

**Comment by aaron-binary** [comment] 2020-10-06 05:52
Hey @deja12,

It could be related to being rate limited. 😞 

In general I'd recommend using DBot (https://app.deriv.com/bot) over Binary Bot as it receives more frequent updates and fixes. For this scenario, I tried reproducing but I'm unable to on my side, so I'd like to ask if you could help me. This will be a somewhat technical explanation, but it would help us immensely.

1. Go to https://bot.binary.com (or https://binary.bot / https://bot.binary.me)
2. Open your developer tools, there's a guide for all the major browsers here https://balsamiq.com/support/faqs/browserconsole/
3. Go to your **Network** tab

<img width="1680" alt="Screenshot 2020-10-06 at 13 43 13" src="https://user-images.githubusercontent.com/44427668/95163284-1dd9a580-07da-11eb-91fe-50276ba53418.png">

4. Press the **Clear** button

<img width="590" alt="Screenshot 2020-10-06 at 13 45 16" src="https://user-images.githubusercontent.com/44427668/95163378-524d6180-07da-11eb-8a58-31068b99e493.png">

5. Start the bot, you'll notice that a new websocket connection is opened.

<img width="569" alt="Screenshot 2020-10-06 at 13 47 16" src="https://user-images.githubusercontent.com/44427668/95163463-8032a600-07da-11eb-9c29-17a74a57ffb4.png">

6. Click the websocket connection and you'll see the messages that are being sent to our servers.

<img width="611" alt="Screenshot 2020-10-06 at 13 48 08" src="https://user-images.githubusercontent.com/44427668/95163581-c425ab00-07da-11eb-8889-70da25877f60.png">

7. Wait until the bot gets stuck, and then once it gets stuck, right click the WS connection and click **Save all as HAR with content**.

<img width="574" alt="Screenshot 2020-10-06 at 13 50 03" src="https://user-images.githubusercontent.com/44427668/95163636-e28ba680-07da-11eb-966c-6f2b2470e0d9.png">

8. Send me an email at aaron@deriv.com, and I'll look into what's happening here.

Thanks in advance,
Aaron

**Comment by deja12** [comment] 2020-10-06 08:07
> Hey @deja12,
> 
> It could be related to being rate limited. 😞
> 
> In general I'd recommend using DBot (https://app.deriv.com/bot) over Binary Bot as it receives more frequent updates and fixes. For this scenario, I tried reproducing but I'm unable to on my side, so I'd like to ask if you could help me. This will be a somewhat technical explanation, but it would help us immensely.
> 
> 1. Go to https://bot.binary.com (or https://binary.bot / https://bot.binary.me)
> 2. Open your developer tools, there's a guide for all the major browsers here https://balsamiq.com/support/faqs/browserconsole/
> 3. Go to your **Network** tab
> 
> <img alt="Screenshot 2020-10-06 at 13 43 13" width="1680" src="https://user-images.githubusercontent.com/44427668/95163284-1dd9a580-07da-11eb-91fe-50276ba53418.png">
> 
> 1. Press the **Clear** button
> 
> <img alt="Screenshot 2020-10-06 at 13 45 16" width="590" src="https://user-images.githubusercontent.com/44427668/95163378-524d6180-07da-11eb-8a58-31068b99e493.png">
> 
> 1. Start the bot, you'll notice that a new websocket connection is opened.
> 
> <img alt="Screenshot 2020-10-06 at 13 47 16" width="569" src="https://user-images.githubusercontent.com/44427668/95163463-8032a600-07da-11eb-9c29-17a74a57ffb4.png">
> 
> 1. Click the websocket connection and you'll see the messages that are being sent to our servers.
> 
> <img alt="Screenshot 2020-10-06 at 13 48 08" width="611" src="https://user-images.githubusercontent.com/44427668/95163581-c425ab00-07da-11eb-8889-70da25877f60.png">
> 
> 1. Wait until the bot gets stuck, and then once it gets stuck, right click the WS connection and click **Save all as HAR with content**.
> 
> <img alt="Screenshot 2020-10-06 at 13 50 03" width="574" src="https://user-images.githubusercontent.com/44427668/95163636-e28ba680-07da-11eb-966c-6f2b2470e0d9.png">
> 
> 1. Send me an email at [aaron@deriv.com](mailto:aaron@deriv.com), and I'll look into what's happening here.
> 
> Thanks in advance,
> Aaron
Thank you for your response. I am seeing this error with over and under as well, I have tried VPS and still getting the same error, I am doing what you have asked, I will email you with the information you asked. Thank you

**Comment by virtusasys** [comment] 2020-10-07 12:51
![image](https://user-images.githubusercontent.com/59830499/95332940-b569f180-08c9-11eb-89d3-c02356e40809.png)
Now Fixed I think...thanks but these strategy ODD Even Bot Freeze,, 2 times,

**Comment by deja12** [comment] 2020-10-07 15:31
I am still having the issue. it stopped after 2 to three trades

**Comment by aaron-binary** [comment] 2020-10-08 06:46
Hey @deja12,

We've released (yet another) fix, could you check again? 

If the issue persists, could you go through the steps in my previous comment and send me the websocket logs?

Regards,
Aaron

**Comment by deja12** [comment] 2020-10-08 07:10
@aaron-binary ok let me test and check. Thank you

**Comment by deja12** [comment] 2020-10-08 07:33
@aaron-binary I ran it for 12 minutes, It working fine. Thank you for you support and quick action. I will check for few more days for longer period of time before going live. Once again Thank you

**Comment by deja12** [comment] 2020-10-08 07:44
@aaron-binary I tried on both, it working fine at binarybot but at Dbot it stopped after 2 to three trades, I have emailed you above information. Kindly check.
Thank you

**Comment by stranger-dev** [comment] 2020-10-13 05:22
@aaron-binary I've had a worse experience with the random stopping bot on **Dbot**, It stops way more frequently than **Binary-Bot**.

The most common errors on the console are: 
`Uncaught (in promise) RateLimit: [ServerError] You have reached the rate limit for proposal_open_contract.`
`Uncaught (in promise) OfferingsValidationError: [ServerError] Trading is not offered for this asset.`

**Closed** 2020-11-16 02:01 UTC
Labels: technical issues
