### ISSUE TITLE
please fix the bot.binary.com webpage does not work.

### ISSUE THREAD

**Issue by lasaidhari** [binary-com/binary-bot#1159] opened 2019-01-31 22:32 UTC
please fix the bot.binary.com webpage does not work.
![bot](https://user-images.githubusercontent.com/34808023/52090012-b15cdb00-25e2-11e9-83b0-0c95033d9b2a.jpg)

**Comment by aaron-binary** [comment] 2019-02-01 01:06
Duplicate of #1155

**Closed by aaron-binary** 2019-02-01 01:06 UTC
