### ISSUE TITLE
who work with cli bot @deriv-api look more easy? and i need help

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#2362] opened 2020-01-25 17:40 UTC
i try to do it but i dont have programmer background. need help.
https://github.com/binary-com/deriv-api/issues/16

https://github.com/binary-com/deriv-api/blob/master/examples/a_simple_bot.js

get account balance is working can repeat many time in loop.
async function main() {
while (1) {
const account = await api.account(token);
const { balance } = account;
console.log(Your current balance is: ${balance.currency} ${balance.display});
}
}
Out put
Your current balance is: USD 13,464.40
Your current balance is: USD 13,464.40
Your current balance is: USD 13,464.40
Your current balance is: USD 13,464.40
Your current balance is: USD 13,464.40
Your current balance is: USD 13,464.40

after add by contract only buy 1 time and stop.
async function main() {
while (1) {
const account = await api.account(token);

    const { balance } = account;

    console.log(`Your current balance is: ${balance.currency} ${balance.display}`);
    const contract = await api.contract({
        contract_type: 'CALL',
        currency: balance.currency,
        amount: 10,
        duration: 5,
        duration_unit: 't',
        symbol: 'R_10',
        basis: 'stake',
    });
    const buy = await contract.buy();
}
}
out put only buy 1 time and stop
Your current balance is: USD 13,473.93
buy and loss
Your current balance is: USD 13,463.93

what im did wrong? all follow example script
It only 1 time order and stop.

**Comment by aaron-binary** [comment] 2020-01-29 01:39
Closing this, as duplicate of https://github.com/binary-com/deriv-api/issues/16

**Closed by aaron-binary** 2020-01-29 01:39 UTC
