### ISSUE TITLE
Contract not closing 

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2356] opened 2020-01-23 05:06 UTC
Sometimes my my contract is not closing and stopped next trades. 

How to fix it ?

![image](https://user-images.githubusercontent.com/32416314/72958003-a985e000-3dcb-11ea-81e4-44a4898e9126.png)

Thanks 
evaroyal84@gmail.com

**Comment by aaron-binary** [comment] 2020-01-23 05:18
Hey @muroyal,

Could you provide your strategy to us? This will help us analyse what may be happening here. You can upload it to https://gist.github.com and post the link here.

Regards,
Aaron

**Comment by hotmatrixx** [comment] 2020-01-23 06:47
hi, @aaron-binary 
This is the exact same issue that I was having in this thread:
https://github.com/binary-com/binary-bot/issues/2355
in fact, I headed back into the github here to post about it.

Interestingly, @muroyal is having this issue now just after I wrote 2 code snippets for him, so I'm wondering if my code is bugged, or showing up a bug in the bot? (I'm presuming that he's using my code)

My bot hasn't locked up; I set up a notification on the 'block on every tick' to fire every 10 seconds, and it is doing so; the bot is simply not closing out the trade correctly.

I've put notifications at the start and end of every block.
it's getting to the end of Block 2, but not closing out and posting from Block 4.
I'm not super happy about posting my bot so I'll try and pare it down and see if it keeps doign the same things.

I am confident that it's on 'your' end, however as it's only an issue on Forex. It doesn't occur on Synthetic Index Options.

**Comment by muroyal** [comment] 2020-01-23 07:23
@hotmatrixx i have not updated your block in my bot it seems it is pending some steps.

I am facing this issue is syntactic indexes..

I have experienced many issues in forex.. 
Like this ..

**Comment by hotmatrixx** [comment] 2020-01-23 08:06
> 
> 
> @hotmatrixx i have not updated your block in my bot it seems it is pending some steps.
> 
> I am facing this issue is syntactic indexes..
> 
> I have experienced many issues in forex..
> Like this ..

That's even more interesting. If you'd used my code and we'd been the only ones to experience it it might have been easier to explain.
I've had no issues on Synthetics, even on bots that lock up regularly on Forex. (Never trade real money on Synthetics! The broker controls them, not the market!)

**Comment by hotmatrixx** [comment] 2020-01-23 08:15
> 
> 
> Hey @muroyal,
> 
> Could you provide your strategy to us? This will help us analyse what may be happening here. You can upload it to https://gist.github.com and post the link here.
> 
> Regards,
> Aaron

So my bot didn't lock up this time, after running for 5h
I came back to check on it, and it locked up on the next trade.
I've been doing some research; there is a newish feature, introduced in Windows10 called UWP which suspends processes that it considers are idle.

The reason my bot worked was because I left it alone, and it was the last thing I clicked, and my mouse was hovering over it. Once I clicked on another window (minesweeper) My task manager suspended the browser window as it was 'too heavy' on resources.

This can be seen in task manager, represented by a little green leaf.

Is it a possible contributor to the potential issue?

**Comment by muroyal** [comment] 2020-01-24 01:50
@aaron-binary Can you provide your email id. I would like to share the bot to you. 

I have two problems 1 is periods longer than data length and 2nd is the bot is not closing contract some times.

**Comment by hotmatrixx** [comment] 2020-01-24 03:40
> 
> 
> @aaron-binary Can you provide your email id. I would like to share the bot to you.
> 
> I have two problems 1 is periods longer than data length and 2nd is the bot is not closing contract some times.

"period longer than data length" is caused by 2 things;
1: you are trying to make a list with more than 1000 entries
2: you are trying to find the 11th value in a list that is only 10 items long.

**Closed** 2020-02-01 18:50 UTC
Labels: technical issues
