### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by renatoaz** [binary-com/binary-bot#586] opened 2018-03-10 18:55 UTC
I put to work the simulation and the Real but it gave difference.

**Comment by binary-ex-machina** [comment] 2018-03-11 16:31
you use the same bot, opening and closing trades on the same spot, both in real and virtual account and have different results?

**Comment by gokula-krishna-dev** [comment] 2018-03-19 07:24
@renatoaz We are not changing the execution of bot depending on real or virtual account. You see the difference only because there is a fluctuations in the market. Try running the bot with virtual and real account in parallel. If you still see the problem reopen this issue with the steps to reproduce it.

**Closed by gokula-krishna-dev** 2018-03-19 07:24 UTC
Labels: question
