### ISSUE TITLE
Can't access balance on "Run once at start"

### ISSUE THREAD

**Issue by aaron-binary** [binary-com/binary-bot#1222] opened 2019-02-15 01:09 UTC
Hey, I'm also having a problem that i belive it might be a bug...
I can't acess my balance on "run once at start" 
In this case I'm trying set the stake to 3% of my balance, but it always says it needs to be a positive number..
If i had it on the "before purchasing" it works fine..

_Originally posted by @mexarrinha in https://github.com/binary-com/binary-bot/issues/1216#issuecomment-463692118_

**Comment by baruga** [comment] 2019-02-15 03:02
@aaron-binary I hope the master master will overcome it immediately and we enjoy trading with bots

**Comment by binary-ex-machina** [comment] 2019-02-15 12:36
@baruga don't run bots for 24 hours, no matter the system or platform, none are connection problem proof.

**Comment by baruga** [comment] 2019-02-16 00:25
@binary-ex-machina If it's like a bot it works not in accordance with the logic that was made after a connection error occurred and the bot continues its last logic. what's the matter ?? Have you ever experienced it ?? if I often experience that.

**Comment by mexarrinha** [comment] 2019-02-17 16:51
@aaron-binary  The issue is fixed now thank you.

**Comment by mexarrinha** [comment] 2019-02-17 17:42
@aaron-binary  don't know if it helps but, i'm testing two bots, on one i can set the balance in "Run once at start" after a few tries, but on the other it doesn't work.

**Comment by bouhali00** [comment] 2019-02-18 23:17
Hi
I encountered the same problem /
at the first run; the bot takes value 0, but after stop and run; it takes the value of balance? !!!!!

**Comment by mexarrinha** [comment] 2019-02-19 09:00
If you are doing rise/fall yes, you try a few times and then it works.
But with digits it doesn't seem to work at all.

**Comment by bouhali00** [comment] 2019-02-21 22:40
I did this trick, and I was able to record my starting balance ...
![balance](https://user-images.githubusercontent.com/44878529/53206754-aa494b80-3629-11e9-85f1-e2ae45eda88e.png)

**Comment by mexarrinha** [comment] 2019-02-22 06:27
Yes i can do that too. But the configuration that i have it to be everything automatic.
It gets the balance;
Calculate target profit;
MaxLoss;
Tradeamount.

But i can only acess it in before purchase, so it will only change after yhe first buy to the values that i want.

**Comment by bouhali00** [comment] 2019-02-22 10:25
I note that this trick allows to have the exact state of balance at to press boutton run, and not after purchase!

**Comment by mexarrinha** [comment] 2019-02-22 11:36
You press play, and your stake is 0.35..
When i press play i want the stake to be 1% of my balance.
I can only set the balance after one trade. 
Some times it works sometimes it doesn't.. 
At the moment i do it manually, but a fix would be appreciated.

**Comment by bouhali00** [comment] 2019-02-22 21:44
If you want to start with 1% of your balance, here an example of block that you can put, ... but it remains to study how you will manage with your balance after gain or loss!

![pourc balance](https://user-images.githubusercontent.com/44878529/53273078-eee8eb80-36ea-11e9-9d9b-b034b44f5674.png)

**Comment by rubenspina** [comment] 2019-02-24 13:19
veja o que montei ontem e deixei a noite trabalhando todos quer uma estabilidade nem se for um valor pequeno e seguro para enviar agora por email $10 sem muita conversa conta para deposito NETELLER 451425729446 o email projetos_10@hotmail.com o email para enviar comprovante de pagamento e projetos_10@hotmail.com envio o arquivo por email.
![captura de tela 2019-02-24 as 09 22 28](https://user-images.githubusercontent.com/30381449/53299191-efca6c00-3815-11e9-9133-a7b533e92b1a.png)
![captura de tela 2019-02-24 as 09 25 29](https://user-images.githubusercontent.com/30381449/53299218-36b86180-3816-11e9-9d86-e87f7dfc07da.png)

**Closed** 2019-08-14 05:26 UTC
Labels: technical issues
