### ISSUE TITLE
 Problems setting up a bot 

### ISSUE THREAD

**Issue by Geanfranco39** [binary-com/binary-bot#2732] opened 2020-04-29 23:07 UTC
Hello I would like to use the bot in the attachment for FOREX, but it gives me an error when I

change to that setting.

Could someone help me program it for forex?

Attachment screenshot
[SAFE 2.xml.zip](https://github.com/binary-com/binary-bot/files/4555251/SAFE.2.xml.zip)
![80497013-e8ca4c80-8937-11ea-9420-b5952a2e4565](https://user-images.githubusercontent.com/64102356/80655381-8020c400-8a4c-11ea-95c6-e531e2de8e45.png)

**Comment by aaron-binary** [comment] 2020-04-30 02:37
Duplicate of https://github.com/binary-com/binary-bot/issues/2725

**Closed by aaron-binary** 2020-04-30 02:37 UTC
Labels: strategy
